### ISSUE TITLE
Fix security vulnerabilities

### ISSUE THREAD

**Issue by chrismaille** [chrismaille/cabrita#5]

**Comment by y4my4my4m** [comment]
@chrisgeru @chrismaille 
Hey Chris, good job with cabrita, it looks like exactly what I need and want.

I was wondering, what kind of security vulnerabilities does cabrita have? I'm wondering how safe it is to use on my home lab.

**Comment by chrismaille** [comment]
Hi y4my4my4m,

Thanks for contact me. At first, I believe its just old dependencies. But I'll update dependencies and double check code on the following days.
